//registro de usuarios ---------------------------------------------
POST http://localhost:3000/user/register-employee HTTP/1.1
content-type: application/json

 {
    "email":"prueba2@gmail.com",
    "password":"prueba1@gmail.com",
    "name":"prueba1",
    "lastName":"prueba1",
    "phone":"8989675634",
    "type":"admin"
 }

###
POST http://localhost:3000/user/register-owner HTTP/1.1
content-type: application/json

 {
    "email":"prueba1@gmail.com",
    "password":"prueba1@gmail.com",
    "name":"prueba1",
    "lastName":"prueba1",
    "phone":"8989675634"
 }

//------------------------------------------------fin
###
//OBTIENE A LOS USUARIOS QUE SON EMPLEADOS (activos e inactivos)
GET http://localhost:3000/vet/userEmp HTTP/1.1

###
//OBTIENE A UN USUARIO POR ID, FUNCIONA PARA EMPLEADOS COMO PARA DUEÑOS (activos)
GET http://localhost:3000/vet/user/65ea852002622db1cc12c5e6 HTTP/1.1

###
//ACTUALIZA LA CONTRASEÑA DEL USUARIO POR ID
PUT http://localhost:3000/vet/user/65f7fd75b9ee319c83c633ef HTTP/1.1
content-type: application/json

{
    "password":"prueba2@gmail.com"
}
###
//ELIMINA AL USUARIO POR ID (CAMBIA ESTADO A 'INACTIVO') IMPIDIENDO EL LOGIN  Y EL UPDATE DE LA CONTRASEÑA
DELETE http://localhost:3000/vet/user/65f7fd75b9ee319c83c633ef HTTP/1.1
//----------------------------------------------------------------------------

###
//OBTIENE A TODOS LOS EMPLEADOS ACTIVOS
GET http://localhost:3000/vet/employee HTTP/1.1

###
//OBTIENE AL EMPLEADO POR ID Y QUE SEA ACTIVO
GET http://localhost:3000/vet/employee/65f7fd75b9ee319c83c633f1 HTTP/1.1

###
//ACTUALIZA EMPELADO POR ID  Y SE ENCUENTRE ACTIVO
PUT http://localhost:3000/vet/employee/65f7fd75b9ee319c83c633f1 HTTP/1.1
content-Type: application/json

{
   "name":"prueba1 v2",
   "lastName":"prueba 1v2",
   "type":"vet"
}

###
//ELIMINA A UN EMPELADO(CAMBAI EL ESTADO A 'INACTIVO') POR ID
DELETE http://localhost:3000/vet/employee/65f7fd75b9ee319c83c633f1 HTTP/1.1
//-----------------------------------------------------------------------------------------

###
//OBTIENE A TODOS LOS DUEÑOS QUE ESTEN ACTIVOS
GET http://localhost:3000/vet/owner HTTP/1.1

###
//OBTIENE AL DUEÑO POR ID Y QUE SE ENCUENTRE ACTIVO
GET http://localhost:3000/vet/owner/65f89848e5a500ae3039e5c5 HTTP/1.1

###
//OBTIENE AL DUEÑO POR ID Y ESTADO 'ACTIVO' 
PUT http://localhost:3000/vet/owner/65f89848e5a500ae3039e5c5 HTTP/1.1
Content-Type: application/json

{
   "name":"prueba1v2",
   "lastName":"prueba1v2",
   "phone":"0987654347"
}

###
DELETE http://localhost:3000/vet/owner/65f89848e5a500ae3039e5c5 HTTP/1.1
###
//-------------------------------------------------------------------------

//OBTIENE A TODAS LAS AMSCOTAS 'ACTIVAS'
GET http://localhost:3000/vet/pet/ HTTP/1.1

###
//OBTIENE A LA MASCOTA POR ID Y ESTADO 'ACTIVO'
GET http://localhost:3000/vet/pet/65f8a33028042092aa600952 HTTP/1.1

###
//REGISTRA A UNA MASCOTA CON RELACION A UN DUEÑO POR SU ID
POST http://localhost:3000/vet/pet/ HTTP/1.1
Content-Type: application/json

{
   "name":"pet4",
   "age":"3",
   "health":"Bueno",
   "gender":"Macho",
   "weight": "7.4",
   "specie":"Felino",
   "ownerId":"65ee552bc0238dc8187b0f75"
}
###
//ACTUALIZA MASCOTA POR ID Y ESTADO 'ACTIVO'
PUT http://localhost:3000/vet/pet/65f8a33028042092aa600952 HTTP/1.1
Content-Type: application/json

{
   "name":"pet4V2",
   "age":"3",
   "health":"Bueno",
   "gender":"Macho",
   "weight": "7.4",
   "specie":"Felino",
   "ownerId":"65ee552bc0238dc8187b0f75"
}

###
//ELIMINA A MASCOTA POR ID (CAMBIA DE ESTADO A INACTIVO)
DELETE  http://localhost:3000/vet/pet/65f8a33028042092aa600952 HTTP/1.1

###
GET http://localhost:3000/vet/product HTTP/1.1

###
//-------------------------------------------------------------post
//OBTIENE TODOS LOS POST PUBLICADOS
GET http://localhost:3000/vet/post HTTP/1.1

###
//OBTIENE POST POR ID
GET http://localhost:3000/vet/post/65fa3d2df258ce805ef37f7b HTTP/1.1

###
//REGISTRA UN POST
POST http://localhost:3000/vet/post HTTP/1.1
Content-Type: application/json

{
   "title":"Bienvenido a la app de Bigotes Pet",
   "description":"Aqui podras estar al dia con los diversos post publicados por nosotros sobre descuentos, avisos y de mas, gracias."
}

###
//MODIFICA POST POR ID
PUT http://localhost:3000/vet/post/65fa3ee6b0d66685ea1c0976 HTTP/1.1
Content-Type: application/json

{
  "title":"POST 2 v2",
   "description":"POST 2 DESCRIPTION v2" 
}

###
//ELIMINA POR ID UN POST
DELETE http://localhost:3000/vet/post/65fa3ee6b0d66685ea1c0976 HTTP/1.1

###
//------------------------------------------------------------------------consults
//METODO PARA VET
//OBTENER TODAS LAS CONSULTAS
GET http://localhost:3000/vet/consult HTTP/1.1

###
//REGISTRAR UNA CONSULTA
POST http://localhost:3000/vet/consult HTTP/1.1
Content-Type: application/json

{
   "petId":"65ee5677ca143fe61e5466c1",
   "vetId":"65f3eba68239d95e4cf0889d",
   "nameVet":"ana",
   "diagnosis":"Fiebre por desidratacion",
   "observations":"",
   "signs":"Temperatura 38 grados, aspecto cansado",
   "treatment":"Permanecer en lugares con sombra, tomar agua limpia y fresca"
}
###
//OBTENER CONSULTA POR ID
GET http://localhost:3000/vet/consult/65fe5a121d52e8c4d89db58a HTTP/1.1

###
//EDITAR CONSULTA
PUT http://localhost:3000/vet/consult/65fe5a121d52e8c4d89db58a HTTP/1.1
Content-Type: application/json

{
   "vetId":"65f3eba68239d95e4cf0889d",
   "nameVet":"ana",
   "diagnosis":"Fiebre por desidratacion y bomitos",
   "observations":"pelaje en buen aspecto",
   "signs":"Temperatura 38 grados, aspecto cansado",
   "treatment":"Permanecer en lugares con sombra, tomar agua limpia y fresca"
 
}
###
//CONSULTAR LISTA DE CONSULTAS REALIZADAS A UNA MASCOTA POR ID
GET http://localhost:3000/owner/consultPet/65ee5677ca143fe61e5466c1 HTTP/1.1
###
//-----------------------------------------------------------------------------medicalHistories
//OBTIENE TODOS LOS HISTORIALES MEDICOS EN GENERAL
GET http://localhost:3000/vet/medical_history HTTP/1.1
###
//OBTIENE EL EL HISTORIAL POR ID
GET http://localhost:3000/vet/medical_history/65ff6c22ecad459855ee6cba HTTP/1.1
###
//REGISTRA UN HISTORIAL NUEVO
POST http://localhost:3000/vet/medical_history HTTP/1.1
Content-Type: application/json

{
   "petId":"65ee5677ca143fe61e5466c1",
   "vetId":"65f3eba68239d95e4cf0889d",
   "description":"vacuna antiravica dosis numero 1",
   "category":"vacunacion"
}
###
//EDITAR HISTORIAL POR ID
PUT http://localhost:3000/vet/medical_history/65ff6c22ecad459855ee6cba HTTP/1.1
Content-Type: application/json

{
   "vetId":"65f3eba68239d95e4cf0889d",
   "description":"vacuna antiravica dosis numero 2",
   "category":"vacunacion"
}
###
//ELIMINAR HISTORIAL POR ID
DELETE http://localhost:3000/vet/medical_history/65ff6c22ecad459855ee6cba HTTP/1.1
###
GET http://localhost:3000/owner/medical_history/65ee5677ca143fe61e5466c1 HTTP/1.1
###

//------------------------------------------------------------------------SALES
//OBTIENE TODAS LAS VENTAS
GET http://localhost:3000/vet/sale HTTP/1.1
###
//OBTIENE VENTA POR ID
GET http://localhost:3000/vet/sale/65ffc2c235c5410f2fb61e64 HTTP/1.1
###
//REGISTRA UNA VENTA
POST http://localhost:3000/vet/sale HTTP/1.1
Content-Type: application/json

{
   "employeeId":"65f3eba68239d95e4cf0889d",
   "ownerId":"65ee552bc0238dc8187b0f75",
   "payments":[
      {
      "productId":"65ee2d3196c19400cb4f7d30",
      "name":"Whiskas",
      "price":250,
      "quantity":2
      },
      {
      "serviceId":"65ee285096c19400cb4f7d12",
      "name":"Baño y Secado",
      "price":150,
      "quantity":1
      }
   ],
   "total":650
}
###
//ELIMINA REGISTRO DE VENTA POR ID
DELETE http://localhost:3000/vet/sale/65ffc2c235c5410f2fb61e64 HTTP/1.1
###
GET http://localhost:3000/owner/my_tickects/65ee552bc0238dc8187b0f75 HTTP/1.1
